// Auto-derived from countries_continents.csv (the provided country list).
// Each entry: flag-icons alpha-2 code + ISO 3166-1 numeric code + display name +
// continent (drives badge color). `num` matches world-atlas country feature ids so
// markers can be resolved to a country (see countryGeo.js). Regenerate if the list
// changes.
export const PASSPORT_COUNTRIES = [
  { code: "af", num: "004", name: "Afghanistan", continent: "Asia" },
  { code: "al", num: "008", name: "Albania", continent: "Europe" },
  { code: "dz", num: "012", name: "Algeria", continent: "Africa" },
  { code: "ad", num: "020", name: "Andorra", continent: "Europe" },
  { code: "ao", num: "024", name: "Angola", continent: "Africa" },
  { code: "ag", num: "028", name: "Antigua and Barbuda", continent: "North America" },
  { code: "ar", num: "032", name: "Argentina", continent: "South America" },
  { code: "am", num: "051", name: "Armenia", continent: "Europe" },
  { code: "au", num: "036", name: "Australia", continent: "Oceania" },
  { code: "at", num: "040", name: "Austria", continent: "Europe" },
  { code: "az", num: "031", name: "Azerbaijan", continent: "Europe" },
  { code: "bs", num: "044", name: "Bahamas", continent: "North America" },
  { code: "bh", num: "048", name: "Bahrain", continent: "Asia" },
  { code: "bd", num: "050", name: "Bangladesh", continent: "Asia" },
  { code: "bb", num: "052", name: "Barbados", continent: "North America" },
  { code: "by", num: "112", name: "Belarus", continent: "Europe" },
  { code: "be", num: "056", name: "Belgium", continent: "Europe" },
  { code: "bz", num: "084", name: "Belize", continent: "North America" },
  { code: "bj", num: "204", name: "Benin", continent: "Africa" },
  { code: "bt", num: "064", name: "Bhutan", continent: "Asia" },
  { code: "bo", num: "068", name: "Bolivia", continent: "South America" },
  { code: "ba", num: "070", name: "Bosnia and Herzegovina", continent: "Europe" },
  { code: "bw", num: "072", name: "Botswana", continent: "Africa" },
  { code: "br", num: "076", name: "Brazil", continent: "South America" },
  { code: "bn", num: "096", name: "Brunei", continent: "Asia" },
  { code: "bg", num: "100", name: "Bulgaria", continent: "Europe" },
  { code: "bf", num: "854", name: "Burkina", continent: "Africa" },
  { code: "mm", num: "104", name: "Burma (Myanmar)", continent: "Asia" },
  { code: "bi", num: "108", name: "Burundi", continent: "Africa" },
  { code: "kh", num: "116", name: "Cambodia", continent: "Asia" },
  { code: "cm", num: "120", name: "Cameroon", continent: "Africa" },
  { code: "ca", num: "124", name: "Canada", continent: "North America" },
  { code: "cv", num: "132", name: "Cape Verde", continent: "Africa" },
  { code: "cf", num: "140", name: "Central African Republic", continent: "Africa" },
  { code: "td", num: "148", name: "Chad", continent: "Africa" },
  { code: "cl", num: "152", name: "Chile", continent: "South America" },
  { code: "cn", num: "156", name: "China", continent: "Asia" },
  { code: "co", num: "170", name: "Colombia", continent: "South America" },
  { code: "km", num: "174", name: "Comoros", continent: "Africa" },
  { code: "cg", num: "178", name: "Congo", continent: "Africa" },
  { code: "cr", num: "188", name: "Costa Rica", continent: "North America" },
  { code: "hr", num: "191", name: "Croatia", continent: "Europe" },
  { code: "cu", num: "192", name: "Cuba", continent: "North America" },
  { code: "cy", num: "196", name: "Cyprus", continent: "Europe" },
  { code: "cz", num: "203", name: "Czechia", continent: "Europe" },
  { code: "cd", num: "180", name: "Democratic Republic of Congo", continent: "Africa" },
  { code: "dk", num: "208", name: "Denmark", continent: "Europe" },
  { code: "dj", num: "262", name: "Djibouti", continent: "Africa" },
  { code: "dm", num: "212", name: "Dominica", continent: "North America" },
  { code: "do", num: "214", name: "Dominican Republic", continent: "North America" },
  { code: "tl", num: "626", name: "East Timor", continent: "Asia" },
  { code: "ec", num: "218", name: "Ecuador", continent: "South America" },
  { code: "eg", num: "818", name: "Egypt", continent: "Africa" },
  { code: "sv", num: "222", name: "El Salvador", continent: "North America" },
  { code: "gq", num: "226", name: "Equatorial Guinea", continent: "Africa" },
  { code: "er", num: "232", name: "Eritrea", continent: "Africa" },
  { code: "ee", num: "233", name: "Estonia", continent: "Europe" },
  { code: "et", num: "231", name: "Ethiopia", continent: "Africa" },
  { code: "fj", num: "242", name: "Fiji", continent: "Oceania" },
  { code: "fi", num: "246", name: "Finland", continent: "Europe" },
  { code: "fr", num: "250", name: "France", continent: "Europe" },
  { code: "ga", num: "266", name: "Gabon", continent: "Africa" },
  { code: "gm", num: "270", name: "Gambia", continent: "Africa" },
  { code: "ge", num: "268", name: "Georgia", continent: "Europe" },
  { code: "de", num: "276", name: "Germany", continent: "Europe" },
  { code: "gh", num: "288", name: "Ghana", continent: "Africa" },
  { code: "gr", num: "300", name: "Greece", continent: "Europe" },
  { code: "gd", num: "308", name: "Grenada", continent: "North America" },
  { code: "gt", num: "320", name: "Guatemala", continent: "North America" },
  { code: "gn", num: "324", name: "Guinea", continent: "Africa" },
  { code: "gw", num: "624", name: "Guinea-Bissau", continent: "Africa" },
  { code: "gy", num: "328", name: "Guyana", continent: "South America" },
  { code: "ht", num: "332", name: "Haiti", continent: "North America" },
  { code: "hn", num: "340", name: "Honduras", continent: "North America" },
  { code: "hk", num: "344", name: "Hong Kong", continent: "Asia" },
  { code: "hu", num: "348", name: "Hungary", continent: "Europe" },
  { code: "is", num: "352", name: "Iceland", continent: "Europe" },
  { code: "in", num: "356", name: "India", continent: "Asia" },
  { code: "id", num: "360", name: "Indonesia", continent: "Asia" },
  { code: "ir", num: "364", name: "Iran", continent: "Asia" },
  { code: "iq", num: "368", name: "Iraq", continent: "Asia" },
  { code: "ie", num: "372", name: "Ireland", continent: "Europe" },
  { code: "il", num: "376", name: "Israel", continent: "Asia" },
  { code: "it", num: "380", name: "Italy", continent: "Europe" },
  { code: "ci", num: "384", name: "Ivory Coast", continent: "Africa" },
  { code: "jm", num: "388", name: "Jamaica", continent: "North America" },
  { code: "jp", num: "392", name: "Japan", continent: "Asia" },
  { code: "jo", num: "400", name: "Jordan", continent: "Asia" },
  { code: "kz", num: "398", name: "Kazakhstan", continent: "Asia" },
  { code: "ke", num: "404", name: "Kenya", continent: "Africa" },
  { code: "ki", num: "296", name: "Kiribati", continent: "Oceania" },
  { code: "kw", num: "414", name: "Kuwait", continent: "Asia" },
  { code: "kg", num: "417", name: "Kyrgyzstan", continent: "Asia" },
  { code: "la", num: "418", name: "Laos", continent: "Asia" },
  { code: "lv", num: "428", name: "Latvia", continent: "Europe" },
  { code: "lb", num: "422", name: "Lebanon", continent: "Asia" },
  { code: "ls", num: "426", name: "Lesotho", continent: "Africa" },
  { code: "lr", num: "430", name: "Liberia", continent: "Africa" },
  { code: "ly", num: "434", name: "Libya", continent: "Africa" },
  { code: "li", num: "438", name: "Liechtenstein", continent: "Europe" },
  { code: "lt", num: "440", name: "Lithuania", continent: "Europe" },
  { code: "lu", num: "442", name: "Luxembourg", continent: "Europe" },
  { code: "mk", num: "807", name: "Macedonia", continent: "Europe" },
  { code: "mg", num: "450", name: "Madagascar", continent: "Africa" },
  { code: "mw", num: "454", name: "Malawi", continent: "Africa" },
  { code: "my", num: "458", name: "Malaysia", continent: "Asia" },
  { code: "mv", num: "462", name: "Maldives", continent: "Asia" },
  { code: "ml", num: "466", name: "Mali", continent: "Africa" },
  { code: "mt", num: "470", name: "Malta", continent: "Europe" },
  { code: "mh", num: "584", name: "Marshall Islands", continent: "Oceania" },
  { code: "mr", num: "478", name: "Mauritania", continent: "Africa" },
  { code: "mu", num: "480", name: "Mauritius", continent: "Africa" },
  { code: "mx", num: "484", name: "Mexico", continent: "North America" },
  { code: "fm", num: "583", name: "Micronesia", continent: "Oceania" },
  { code: "md", num: "498", name: "Moldova", continent: "Europe" },
  { code: "mc", num: "492", name: "Monaco", continent: "Europe" },
  { code: "mn", num: "496", name: "Mongolia", continent: "Asia" },
  { code: "me", num: "499", name: "Montenegro", continent: "Europe" },
  { code: "ma", num: "504", name: "Morocco", continent: "Africa" },
  { code: "mz", num: "508", name: "Mozambique", continent: "Africa" },
  { code: "na", num: "516", name: "Namibia", continent: "Africa" },
  { code: "nr", num: "520", name: "Nauru", continent: "Oceania" },
  { code: "np", num: "524", name: "Nepal", continent: "Asia" },
  { code: "nl", num: "528", name: "Netherlands", continent: "Europe" },
  { code: "nz", num: "554", name: "New Zealand", continent: "Oceania" },
  { code: "ni", num: "558", name: "Nicaragua", continent: "North America" },
  { code: "ne", num: "562", name: "Niger", continent: "Africa" },
  { code: "ng", num: "566", name: "Nigeria", continent: "Africa" },
  { code: "kp", num: "408", name: "North Korea", continent: "Asia" },
  { code: "no", num: "578", name: "Norway", continent: "Europe" },
  { code: "om", num: "512", name: "Oman", continent: "Asia" },
  { code: "pk", num: "586", name: "Pakistan", continent: "Asia" },
  { code: "pw", num: "585", name: "Palau", continent: "Oceania" },
  { code: "pa", num: "591", name: "Panama", continent: "North America" },
  { code: "pg", num: "598", name: "Papua New Guinea", continent: "Oceania" },
  { code: "py", num: "600", name: "Paraguay", continent: "South America" },
  { code: "pe", num: "604", name: "Peru", continent: "South America" },
  { code: "ph", num: "608", name: "Philippines", continent: "Asia" },
  { code: "pl", num: "616", name: "Poland", continent: "Europe" },
  { code: "pt", num: "620", name: "Portugal", continent: "Europe" },
  { code: "qa", num: "634", name: "Qatar", continent: "Asia" },
  { code: "ro", num: "642", name: "Romania", continent: "Europe" },
  { code: "ru", num: "643", name: "Russia", continent: "Asia" },
  { code: "rw", num: "646", name: "Rwanda", continent: "Africa" },
  { code: "kn", num: "659", name: "Saint Kitts and Nevis", continent: "North America" },
  { code: "lc", num: "662", name: "Saint Lucia", continent: "North America" },
  { code: "vc", num: "670", name: "Saint Vincent and the Grenadines", continent: "North America" },
  { code: "ws", num: "882", name: "Samoa", continent: "Oceania" },
  { code: "sm", num: "674", name: "San Marino", continent: "Europe" },
  { code: "st", num: "678", name: "Sao Tome and Principe", continent: "Africa" },
  { code: "sa", num: "682", name: "Saudi Arabia", continent: "Asia" },
  { code: "sn", num: "686", name: "Senegal", continent: "Africa" },
  { code: "rs", num: "688", name: "Serbia", continent: "Europe" },
  { code: "sc", num: "690", name: "Seychelles", continent: "Africa" },
  { code: "sl", num: "694", name: "Sierra Leone", continent: "Africa" },
  { code: "sg", num: "702", name: "Singapore", continent: "Asia" },
  { code: "sk", num: "703", name: "Slovakia", continent: "Europe" },
  { code: "si", num: "705", name: "Slovenia", continent: "Europe" },
  { code: "sb", num: "090", name: "Solomon Islands", continent: "Oceania" },
  { code: "so", num: "706", name: "Somalia", continent: "Africa" },
  { code: "za", num: "710", name: "South Africa", continent: "Africa" },
  { code: "kr", num: "410", name: "South Korea", continent: "Asia" },
  { code: "ss", num: "728", name: "South Sudan", continent: "Africa" },
  { code: "es", num: "724", name: "Spain", continent: "Europe" },
  { code: "lk", num: "144", name: "Sri Lanka", continent: "Asia" },
  { code: "sd", num: "729", name: "Sudan", continent: "Africa" },
  { code: "sr", num: "740", name: "Suriname", continent: "South America" },
  { code: "sz", num: "748", name: "Swaziland", continent: "Africa" },
  { code: "se", num: "752", name: "Sweden", continent: "Europe" },
  { code: "ch", num: "756", name: "Switzerland", continent: "Europe" },
  { code: "sy", num: "760", name: "Syria", continent: "Asia" },
  { code: "tw", num: "158", name: "Taiwan", continent: "Asia" },
  { code: "tj", num: "762", name: "Tajikistan", continent: "Asia" },
  { code: "tz", num: "834", name: "Tanzania", continent: "Africa" },
  { code: "th", num: "764", name: "Thailand", continent: "Asia" },
  { code: "tg", num: "768", name: "Togo", continent: "Africa" },
  { code: "to", num: "776", name: "Tonga", continent: "Oceania" },
  { code: "tt", num: "780", name: "Trinidad and Tobago", continent: "North America" },
  { code: "tn", num: "788", name: "Tunisia", continent: "Africa" },
  { code: "tr", num: "792", name: "Turkey", continent: "Europe" },
  { code: "tm", num: "795", name: "Turkmenistan", continent: "Asia" },
  { code: "tv", num: "798", name: "Tuvalu", continent: "Oceania" },
  { code: "ug", num: "800", name: "Uganda", continent: "Africa" },
  { code: "ua", num: "804", name: "Ukraine", continent: "Europe" },
  { code: "ae", num: "784", name: "United Arab Emirates", continent: "Asia" },
  { code: "gb", num: "826", name: "United Kingdom", continent: "Europe" },
  { code: "us", num: "840", name: "United States", continent: "North America" },
  { code: "uy", num: "858", name: "Uruguay", continent: "South America" },
  { code: "uz", num: "860", name: "Uzbekistan", continent: "Asia" },
  { code: "vu", num: "548", name: "Vanuatu", continent: "Oceania" },
  { code: "va", num: "336", name: "Vatican City", continent: "Europe" },
  { code: "ve", num: "862", name: "Venezuela", continent: "South America" },
  { code: "vn", num: "704", name: "Vietnam", continent: "Asia" },
  { code: "ye", num: "887", name: "Yemen", continent: "Asia" },
  { code: "zm", num: "894", name: "Zambia", continent: "Africa" },
  { code: "zw", num: "716", name: "Zimbabwe", continent: "Africa" },
];
