import { useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import LogoMark from '../components/LogoMark';

const DSAR = 'https://app.termly.io/dsar/5585c578-e9c1-4524-ad2d-dfb7e637a491';

// Clean, dark-theme rendering of the Imprint privacy policy. The source policy
// was generated by Termly with light-mode styling; this restates the same
// content using the app's theme tokens so it's readable and on-brand.
export default function PrivacyPolicy() {
  const navigate = useNavigate();

  // Land at the top of the policy regardless of prior scroll position.
  useEffect(() => { window.scrollTo(0, 0); }, []);

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--text)' }}>
      <div style={{ maxWidth: '760px', margin: '0 auto', padding: '32px 24px 96px' }}>
        <button
          className="btn btn-ghost"
          style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', marginBottom: '32px' }}
          onClick={() => navigate(-1)}
        >
          <ArrowLeft size={16} /> Back
        </button>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
          <LogoMark size={32} />
          <h1 style={{ fontFamily: 'var(--font-display)', fontSize: '34px', margin: 0, letterSpacing: '-1px' }}>
            Privacy Policy
          </h1>
        </div>
        <p style={{ color: 'var(--muted)', fontSize: '14px', margin: '0 0 32px' }}>Last updated June 20, 2026</p>

        <p style={s.body}>
          This Privacy Notice for Imprint ("we," "us," or "our") describes how and why we might access,
          collect, store, use, and/or share ("process") your personal information when you use our
          services ("Services"), including when you:
        </p>
        <ul style={s.ul}>
          <li>Visit our website at{' '}
            <a style={s.link} href="https://imprint-wheat.vercel.app/home" target="_blank" rel="noreferrer">
              https://imprint-wheat.vercel.app/home
            </a>, or any website of ours that links to this Privacy Notice
          </li>
          <li>Download and use our mobile application (Imprint), or any other application of ours that links to this Privacy Notice</li>
          <li>Use Imprint. Imprint maps every place you've ever been — turning your travels into a living portrait of your world. See your coverage, explore what's left, and share the journey.</li>
          <li>Engage with us in other related ways, including any marketing or events</li>
        </ul>
        <p style={s.body}>
          <strong>Questions or concerns?</strong> Reading this Privacy Notice will help you understand your
          privacy rights and choices. If you do not agree with our policies and practices, please do not use
          our Services. If you still have any questions or concerns, please contact us through{' '}
          <Link style={s.link} to="/contact">our contact form</Link>.
        </p>

        <Section title="Summary of key points">
          <p style={s.body}>
            <strong>What personal information do we process?</strong> When you visit, use, or navigate our
            Services, we may process personal information depending on how you interact with us and the
            Services, the choices you make, and the features you use.
          </p>
          <p style={s.body}>
            <strong>Do we process any sensitive personal information?</strong> We do not process sensitive
            personal information.
          </p>
          <p style={s.body}>
            <strong>Do we collect any information from third parties?</strong> We do not collect any
            information from third parties.
          </p>
          <p style={s.body}>
            <strong>How do we process your information?</strong> We process your information to provide,
            improve, and administer our Services, communicate with you, for security and fraud prevention,
            and to comply with law. We process your information only when we have a valid legal reason to do so.
          </p>
          <p style={s.body}>
            <strong>How do we keep your information safe?</strong> We have adequate organizational and
            technical processes and procedures in place to protect your personal information. However, no
            electronic transmission or storage technology can be guaranteed to be 100% secure.
          </p>
          <p style={s.body}>
            <strong>What are your rights?</strong> Depending on where you are located, applicable privacy law
            may mean you have certain rights regarding your personal information.
          </p>
        </Section>

        <Section title="1. What information do we collect?">
          <p style={s.body}>
            <strong>Personal information you disclose to us.</strong> We collect personal information that you
            voluntarily provide to us when you register on the Services, express an interest in obtaining
            information about us or our products and Services, participate in activities on the Services, or
            otherwise when you contact us. The personal information we collect may include:
          </p>
          <ul style={s.ul}>
            <li>names</li>
            <li>email addresses</li>
            <li>usernames</li>
            <li>passwords</li>
          </ul>
          <p style={s.body}>
            <strong>Sensitive Information.</strong> We do not process sensitive information.
          </p>
          <p style={s.body}>
            <strong>Application Data.</strong> If you use our application(s), we may collect the following if
            you grant access or permission:
          </p>
          <ul style={s.ul}>
            <li><em>Geolocation Information.</em> We may request access or permission to track location-based
              information from your mobile device, either continuously or while you are using our mobile
              application(s), to provide certain location-based services. You can change our access or
              permissions in your device's settings.
            </li>
          </ul>
          <p style={s.body}>
            This information is primarily needed to maintain the security and operation of our application(s),
            for troubleshooting, and for our internal analytics and reporting purposes. All personal
            information that you provide to us must be true, complete, and accurate, and you must notify us of
            any changes to such personal information.
          </p>
        </Section>

        <Section title="2. How do we process your information?">
          <p style={s.body}>
            We process your information to provide, improve, and administer our Services, communicate with
            you, for security and fraud prevention, and to comply with law. This includes processing your
            information to facilitate account creation and authentication and otherwise manage user accounts,
            and to save or protect an individual's vital interest, such as to prevent harm. We may also
            process your information for other purposes only with your prior explicit consent.
          </p>
        </Section>

        <Section title="3. What legal bases do we rely on to process your information?">
          <p style={s.body}>
            We only process your personal information when we believe it is necessary and we have a valid
            legal reason (i.e., legal basis) to do so under applicable law, like with your consent, to comply
            with laws, to provide you with services, to protect your rights, or to fulfill our legitimate
            business interests. Depending on your location, the legal bases may include consent (which you can
            withdraw at any time), legal obligations, and vital interests.
          </p>
        </Section>

        <Section title="4. When and with whom do we share your personal information?">
          <p style={s.body}>
            We may need to share your personal information in the following situations:
          </p>
          <ul style={s.ul}>
            <li><strong>Business Transfers.</strong> We may share or transfer your information in connection
              with, or during negotiations of, any merger, sale of company assets, financing, or acquisition
              of all or a portion of our business to another company.
            </li>
          </ul>
        </Section>

        <Section title="5. Do we use cookies and other tracking technologies?">
          <p style={s.body}>
            We may use cookies and similar tracking technologies (like web beacons and pixels) to gather
            information when you interact with our Services. Some online tracking technologies help us
            maintain the security of our Services and your account, prevent crashes, fix bugs, save your
            preferences, and assist with basic site functions. You can usually set your browser to remove or
            reject cookies; doing so could affect certain features of our Services.
          </p>
        </Section>

        <Section title="6. How long do we keep your information?">
          <p style={s.body}>
            We will only keep your personal information for as long as it is necessary for the purposes set
            out in this Privacy Notice, unless a longer retention period is required or permitted by law. No
            purpose in this notice will require us keeping your personal information for longer than the period
            of time in which users have an account with us. When we have no ongoing legitimate business need to
            process your personal information, we will either delete or anonymize it.
          </p>
        </Section>

        <Section title="7. How do we keep your information safe?">
          <p style={s.body}>
            We have implemented appropriate and reasonable technical and organizational security measures
            designed to protect the security of any personal information we process. However, despite our
            safeguards, no electronic transmission over the Internet or information storage technology can be
            guaranteed to be 100% secure. You should only access the Services within a secure environment.
          </p>
        </Section>

        <Section title="8. Do we collect information from minors?">
          <p style={s.body}>
            We do not knowingly collect, solicit data from, or market to children under 18 years of age, nor
            do we knowingly sell such personal information. By using the Services, you represent that you are
            at least 18 or that you are the parent or guardian of such a minor and consent to such minor
            dependent's use of the Services. If we learn that personal information from users less than 18
            years of age has been collected, we will deactivate the account and take reasonable measures to
            promptly delete such data. If you become aware of any data we may have collected from children
            under age 18, please contact us through <Link style={s.link} to="/contact">our contact form</Link>.
          </p>
        </Section>

        <Section title="9. What are your privacy rights?">
          <p style={s.body}>
            Depending on your state or region of residence, you have rights that allow you greater access to
            and control over your personal information. These may include the right to request access and
            obtain a copy of your personal information, to request rectification or erasure, to restrict
            processing, to data portability, and not to be subject to automated decision-making. You may
            review, change, or terminate your account at any time. To withdraw your consent, or to make a
            request, you can contact us using the details below.
          </p>
        </Section>

        <Section title="10. Controls for do-not-track features">
          <p style={s.body}>
            Most web browsers and some mobile operating systems and applications include a Do-Not-Track
            ("DNT") feature you can activate. At this stage, no uniform technology standard for recognizing
            and implementing DNT signals has been finalized. As such, we do not currently respond to DNT
            browser signals or any other mechanism that automatically communicates your choice not to be
            tracked online.
          </p>
        </Section>

        <Section title="11. Do United States residents have specific privacy rights?">
          <p style={s.body}>
            If you are a resident of certain US states, you may have the right to request access to and
            receive details about the personal information we maintain about you and how we have processed it,
            correct inaccuracies, get a copy of, or delete your personal information, and to withdraw your
            consent. We have not sold or shared personal information to third parties for a business or
            commercial purpose, and will not do so in the future. To exercise these rights, you can submit a{' '}
            <a style={s.link} href={DSAR} target="_blank" rel="noreferrer">data subject access request</a>{' '}
            or reach us through <Link style={s.link} to="/contact">our contact form</Link>.
          </p>
        </Section>

        <Section title="12. Do we make updates to this notice?">
          <p style={s.body}>
            Yes, we will update this notice as necessary to stay compliant with relevant laws. The updated
            version will be indicated by an updated "Revised" date. If we make material changes, we may notify
            you either by prominently posting a notice or by directly sending you a notification.
          </p>
        </Section>

        <Section title="13. How can you contact us about this notice?">
          <p style={s.body}>
            If you have questions or comments about this notice, you may reach us through{' '}
            <Link style={s.link} to="/contact">our contact form</Link>.
          </p>
        </Section>

        <Section title="14. How can you review, update, or delete the data we collect from you?">
          <p style={s.body}>
            Based on the applicable laws of your country or state of residence, you may have the right to
            request access to the personal information we collect from you, details about how we have
            processed it, correct inaccuracies, or delete your personal information. To request to review,
            update, or delete your personal information, please submit a{' '}
            <a style={s.link} href={DSAR} target="_blank" rel="noreferrer">data subject access request</a>.
          </p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <section style={{ marginTop: '40px' }}>
      <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '22px', margin: '0 0 12px', letterSpacing: '-0.5px' }}>
        {title}
      </h2>
      {children}
    </section>
  );
}

const s = {
  body: { fontSize: '15px', lineHeight: 1.7, color: 'var(--muted)', margin: '0 0 16px' },
  ul: { fontSize: '15px', lineHeight: 1.7, color: 'var(--muted)', margin: '0 0 16px', paddingLeft: '20px' },
  link: { color: 'var(--accent)', wordBreak: 'break-word' },
};
